spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shopping
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

file:
  dir: D:/uploadLocation/
